---
title: "04 SIR Simulation : n = 10k"
author: "Yohei Kiguchi"
format: html
editor: visual
---

# 05 Simulation : n = 10k (Epidemic Model)

## 1. Setup & Data Import

```{r setup}
library(tidyverse)
library(here)
library(grid) 
library(Matrix)
library(tictoc)
library(igraph)

func_path = here('scripts', 'src')
rds_path = here('data', 'processed')
plot_path = here('output')

source(here(func_path, 'model_matrix_M2.R'))
source(here(func_path, 'model_BM.R'))
source(here(func_path, 'SIR_sim_func.R'))


N = 10000
I0 = 5
R0 = 2.5
d = 7
sim_period = 150
num_simulations = 100 

nodes = readRDS(here(rds_path, 'nodes_10k.rds'))

# Model 1
model_1 = readRDS(here(rds_path, 'BM_longrun1_20260303_064355.rds'))

# Model 2
model_2 = readRDS(here(rds_path,  'M2_Adaptive_Matrix_18_20260327_191045.rds'))
```

### Clean Posterior Distribution

**Model 1**

```{r model 1 clean up}
chain_m1 = model_1$chain

burn_in_ind = floor(model_1$config$n_iter * 0.2)
chain_m1 = chain_m1[-(1 : burn_in_ind), ]
```

**Model 2**

```{r model 2 clean up}
chain_m2 = model_2$chain

burn_in_ind = floor(model_2$config$n_iter * 0.2)
chain_m2 = chain_m2[-(1 : burn_in_ind), ]
```

## 2. Network Generation

```{r generate-networks}

tic("Total Network Generation (100 runs)")

cat("Generating Model 1...\n")
static_data_m1 = get_static_data_bm(nodes)

sim_adj_list_m1 = generate_sim_networks(
  clean_chain = chain_m1, 
  static_data = static_data_m1,
  N = N,
  num_sims = num_simulations,
  seed = 100,
  network_func = generate_network_bm
)


cat("Generating Model 2...\n")
static_data_m2 = get_static_data_m2_5(nodes, n_school = c(1, 1, 3, 4))

sim_adj_list_m2 = generate_sim_networks(
  clean_chain = chain_m2, 
  static_data = static_data_m2,
  N = N,
  num_sims = num_simulations,
  seed = 200, 
  network_func = generate_network_m2_3
)


cat("Generating Erdos-Renyi...\n")
er_adj_list = generate_random_networks_empirical(
  N = N, 
  target_k = 13.5, 
  num_sims = num_simulations, 
  seed = 300
)

toc()

saveRDS(sim_adj_list_m1, file.path(rds_path, "sim_adj_list_m1.rds"))
saveRDS(sim_adj_list_m2, file.path(rds_path, "sim_adj_list_m2.rds"))
saveRDS(er_adj_list,     file.path(rds_path, "er_adj_list.rds"))
```

## 3. Run Simulations (4 Models)

```{r read networks}
sim_adj_list_m1 = readRDS(here(rds_path, 'sim_adj_list_m1.rds'))
sim_adj_list_m2 = readRDS(here(rds_path, 'sim_adj_list_m2.rds'))
er_adj_list     = readRDS(here(rds_path, 'er_adj_list.rds'))
```

```{r run-simulations}
tic("Total Simulation Time")

# 1. Mean Field
set.seed(400)
res_mean_field = replicate(num_simulations, 
                           run_mean_field_sir(N = N, num_init_infected = I0, period = sim_period, R0 = R0, d = d), 
                           simplify = FALSE)

# 2. Erdos-Renyi
res_er = stochastic_sir_simulations(er_adj_list, R0 = R0, d = d, period = sim_period, num_init_infected = I0, init_method = "random", seed = 500)

# 3. Model 1
res_m1 = stochastic_sir_simulations(sim_adj_list_m1, R0 = R0, d = d, period = sim_period, num_init_infected = I0, init_method = "degree", seed = 600)

# 4. Model 2
res_m2 = stochastic_sir_simulations(sim_adj_list_m2, R0 = R0, d = d, period = sim_period, num_init_infected = I0, init_method = "degree", seed = 700)

toc()
```

```{r}
saveRDS(res_mean_field, here(rds_path, "res_mean_field_r0_25.rds"))
saveRDS(res_er, here(rds_path, "res_er_r0_25.rds"))
saveRDS(res_m1, here(rds_path, "res_m1_r0_25.rds"))
saveRDS(res_m2, here(rds_path, "res_m2_r0_25.rds"))
```
